# Generated by Django 2.2.7 on 2019-11-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petalos', '0003_remove_flor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='estado',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
