# Generated by Django 2.2.7 on 2019-12-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petalos', '0004_flor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='stock',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
