# Generated by Django 2.2.7 on 2019-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petalos', '0005_flor_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flor',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flor',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
