# Generated by Django 2.2.7 on 2019-12-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petalos', '0007_auto_20191207_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flor',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flor',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
