# Generated by Django 2.2.7 on 2019-12-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petalos', '0008_auto_20191207_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
