# Generated by Django 2.2.6 on 2019-12-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Petalos', '0009_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flor',
            new_name='Floreria',
        ),
    ]
